# Generated by Django 4.2.7 on 2023-11-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('topic_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('heading_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('heading_name', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('rank', models.CharField(max_length=255)),
                ('mapc', models.CharField(max_length=255)),
                ('article_name', models.CharField(max_length=255)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.heading')),
                ('parrent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.article')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
        ),
    ]
